### ISSUE TITLE
Vertical bars in plot(diagnostic=TRUE)

### ISSUE THREAD

**Issue by pbiecek** [rkillick/changepoint#10]
Would it be possible to pass graphical parameters like 'type="h"' to plot() function?
(‘histogram’ like (or ‘high-density’) vertical lines)

Like in 

```
v1.crops=cpt.var(ftse100$V2, method="PELT", penalty="CROPS", pen.value=c(5,500))
plot(v1.crops, diagnostic=TRUE, type="h")
```

Maybe it will be easier to compare drops in test statistics for different n.o. changepoints.

**Comment by rkillick** [comment]
Thanks to hoxo-m for the changes to complete this request.
