### ISSUE TITLE
cpt.mean() provides index of last observation of regime, not first?

### ISSUE THREAD

**Issue by akbertram** [rkillick/changepoint#13]
According to the documentation:

> A changepoint is denoted as the first observation of the new segment / regime.

However, it looks like the cpt.mean functions return the _last_ index of each segment. For example:

```
> x <- c(rnorm(n=10, 100), rnorm(n=10, 50))
> cpx <- cpt.mean(x)
> cpts(cpx)
> [1] 10
```

The tenth element is the last element of the series generated from a normal distribution with mean of 100. The eleventh element is the _first_ element of the new segment with a mean of 50, right?

**Comment by rkillick** [comment]
As per our research papers we define the first segment as 1,...\tau_1, second segment as \tau_1 +1, ..., \tau_2 and so you are correct that the documentation is incorrect.
This has been corrected in version 2.2.3.  Thanks for reporting it.

**Comment by akbertram** [comment]
Brilliant! Thanks for the clarification. 
I'm using the package to do automated performance regression analysis and it is super useful:
http://packages.renjin.org/benchmarks/machine/gce-n1-standard-4/benchmark/att/fft

**Comment by rkillick** [comment]
Thanks for letting me know how you are using the package.  I've been involved with a project looking at benchmarking VMs using changepoint analysis, it might be of interest:
https://arxiv.org/abs/1602.00602

Keep in touch.

**Comment by akbertram** [comment]
Thanks! That's a super helpful reference.
