### ISSUE TITLE
no way to cpt.mean cusum without warning

### ISSUE THREAD

**Issue by jrounds** [rkillick/changepoint#15]
https://github.com/rkillick/changepoint/blob/8c9c28011f16facbb9507e49fbfa3b6312ebcf08/R/cpt.R#L41

Can't use cpt.mean cusum without warning under any parameterization.  Seems like at least one call to cpt.mean with cusum should not generate a warning?

**Comment by rkillick** [comment]
You are correct, this warning should be inside the single.mean.cusum function where we evaluate the penalty.  The cusum method is currently being ported to changepoint.np so we will incorporate this into that transfer.  Thanks for the feedback :+1:

**Comment by rkillick** [comment]
Moved to the changepoint.np issue list.

**Comment by abrajeffers** [comment]
Does this mean that CUSUM does not work in the changepoint package?  Is the CUSUM test available yet in changepoint.np?  I don't see it in the documentation.

**Comment by rkillick** [comment]
The CUSUM method works it is just that the warning is issued for all calls whereas when you use penalty="Manual" it shouldn't issue a warning.  The method itself is sound, it is just that a warning is given to highlight the traditional penalties like MBIC (default), SIC, etc. are not on the same scale as the test statistic and thus are not suitable where a user my expect them to be.  This is for all CUSUM procedures, not just those implemented in changepoint.

**Comment by rkillick** [comment]
On the move to changepoint.np, we have taken the view to merge the two packages and so all methods will be in changepoint from the next release.

**Comment by mhofert** [comment]
Hi Rebecca. It seems you haven't updated the package on CRAN since (it's published on 2016-10-04), so that warning is still there by default. When will 'changepoint' be updated on CRAN?

**Comment by rkillick** [comment]
Thanks for the nudge.  It is hard to prioritize software releases when we have many other priorities as academics.  We have managed to get some staff time on the package over the next few months so, hopefully, a new release will be put out by the end of the year.
