### ISSUE TITLE
Issue PELT with CUSUM

### ISSUE THREAD

**Issue by usercluster** [rkillick/changepoint#16]
Hi,
I have a quick question: why isn't it possible to use the PELT algorithm with the CUSUM statistics? What would you suggest to use for PELT when it's not possible to make any assumption on the distribution of the data?

Thanks,
SR

**Comment by rkillick** [comment]
Hi SR,

It isn't possible to use PELT with the CUSUM as you can't write it in a way to satisfy the assumptions that PELT requires (additive segments with the inclusion of a changepoint guaranteed to improve the segmentation).
I would advise you use the changepoint.np package.  In there there is an "empirical_distribution" cost function that works with PELT.  It is based off the likelihood of empirical quantiles.

Thanks,
Rebecca
