### ISSUE TITLE
Info on CUSUM

### ISSUE THREAD

**Issue by usercluster** [rkillick/changepoint#17]
Good morning,
I have a question regarding the application of CUSUM in combination with Binary Segmentation. I read on the manual that this is suggested when it's not possible to make assumptions regarding the distribution of the data. Could you please suggest me a source where I can find the theoretical background on this?
I have already checked the material indicated in Page (1954) but the assumptions in that case are stronger.

Thanks a lot for your help,
SR

**Comment by rkillick** [comment]
Apologies for the delay in reply.

https://books.google.co.uk/books?isbn=1439838208
https://books.google.co.uk/books?isbn=9401581630

The above two books thoroughly cover the theoretical underpinnings of the CUSUM method.

Thanks,
Rebecca
