### ISSUE TITLE
Statistical significance of Changepoints

### ISSUE THREAD

**Issue by Liliputian** [rkillick/changepoint#18]
Hi,

I am currently using the changepoint package in R in detecting changepoints in the mean and variance of a rainfall time series.

I would like to ask how can I estimate the statistical significance of the detected change points?
Are the detected change points already significant?

The data can be downloaded here:
https://www.dropbox.com/s/bihcvdlnac3agaa/clim.csv?dl=0

Im using the following commands to get the changepoints.
b=cpt.meanvar(test,"Manual",pen.value="1.5*log(n)",method="BinSeg",Q=2,test.stat="Normal")

I have read the manual and tutorial from this link:
http://members.cbio.mines-paristech.fr/~thocking/change-tutorial/RK-CptWorkshop.html
But it did not mention about the significance of the changepoints.

I''ll appreciate any help.

**Comment by rkillick** [comment]
Thanks for your interest in the changepoint package.

The notion of significance of changepoints isn't as simple as one might first imagine.  For a single changepoint it is easier to define significance as the confidence of the changepoint.  But in a hypothesis framework is the null that there is 0 changepoints verses the alternative of 1 changepoint?  Or is it the null of a changepoint at n (i.e. no changes) and the alternative is a changepoint at tau?

Moving forward to multiple changepoints the concept becomes complicated further.  The significance of a single changepoint location is not trivial.  Regardless of the estimation method the significance of a single changepoint depends on the other changepoints that have been identified.
You can visualize this by thinking of an up-down-up process.  If two changepoints are identified then it does not make sense to say that the second is not significant and remove it as this will likely make the first not significant also, even if strongly significant when the second is present.
You could consider the significance of a set of changepoints but then you need to consider what your null and alternative hypothesis are and will likely have nested hypothesis, 0vs1+, 0,1vs2+,....

This is why the code does not provide significance levels for anything but the single changepoint case.

Having said this you can get a confidence set for the changepoint locations that can give you an idea of uncertainty in estimation.  Whilst not a significance level it is informative as to how much inference you might like to place on a single changepoint.

Not directly in your question but you mention that you are modelling rainfall series.  In my experience these contain autocorrelation and thus you definitely don't want to be using Binary Segmentation (which reacts poorly when the independence assumption is violated) and you may want to consider using the EnvCpt package which contains models that fit AR(1) and AR(2) and also give a decision between mean/trend/AR(1)/AR(2)/changepoint models and all combinations thereof.

Thanks for your question and interest in the package.

**Comment by Liliputian** [comment]
I'm sorry for the multiple emails. I was just worried that the email in the documentation is still active or not that is why I sent to multiple platforms.

Many thanks for the response. I understand this completely.
:-)
