### ISSUE TITLE
minor issue on documenation on where changepoints 

### ISSUE THREAD

**Issue by stephens999** [rkillick/changepoint#25]
thanks for the very nice package!

I was a little mislead by the statement "A changepoint is denoted as the first observation of the new segment / regime." in `?cpt.mean`

I interpreted this as meaning that a changepoint at 100 means that there is a change between 99 and 100. But it seems that in fact it means there is a change between 100 and 101?

**Comment by rkillick** [comment]
This has been corrected to "A changepoint is the last observation of the current segment" (not sure when as I think that I did this and forgot to close this issue - silly me!).
This means that if you do c(rnorm(100),rnorm(100,5)) as the data then the changepoint you expect to get is 100 and the change is between observations 100 and 101.
