### ISSUE TITLE
non-intuitive error for `cpt.mean(..., method=segneigh)`

### ISSUE THREAD

**Issue by TrashBirdEcology** [rkillick/changepoint#31]
I receive the following error when trying to run `cpt.mean(x, method="SegNeigh")`:

`Error in multiple.mean.norm(data, mul.method = method, penalty, pen.value,  : 
  MBIC penalty not implemented for SegNeigh method, please choose an alternative penalty`

The error is not intuitive and I am  not sure which function this is coming from (tried (barely) to located in the package R files without success). 

Would be great to either fix the bug and/or update the error. If the former, note that this command (cpt.mean + SegNeigh) is highlighted in your [documentation](https://cran.r-project.org/web/packages/changepoint/changepoint.pdf).

Thanks!

**Comment by rkillick** [comment]
The error is telling you that the default penalty "MBIC" is not a valid penalty choice for method="SegNeigh".  This check is made in the multiple.mean.norm function which is a sub-function of cpt.mean.
Unfortunately I can't change the location where the error is triggered as the back-end of the package is modular.  But I believe the error itself is both descriptive and also giving an indication of how to fix it.

To not get the error you just need to set a non-default penalty, e.g. `cpt.mean(x,method="SegNeigh",penalty="SIC")`

Please bear in mind that when using SegNeigh you will always receive a warning as it is not a computationally efficient method.  It was included for the original comparison when PELT was introduced.  It is considerable work to keep this updated with the development of the package and so in the next large version release (due late Summer/ early Autumn 2019) this functionality will be removed.

**Comment by TrashBirdEcology** [comment]
Great, I figured it was on my end. Thanks a lot!
Jessica L. Burnett, M.Sc.
Ph.D. Candidate
GitHub <http://github.com/trashbirdecology>
CV/Resume <https://github.com/TrashBirdEcology/cv/tree/master/extendedCV>
Nebraska Cooperative Fish & Wildlife Research Unit
<http://snr.unl.edu/necoopunit/>
School of Natural Resources
University of Nebraska-Lincoln
+1.352.792.5425


<http://snr.unl.edu/necoopunit/>
