### ISSUE TITLE
typo in error message

### ISSUE THREAD

**Issue by konradmayer** [rkillick/changepoint#37]
there appears to be a typo in the error message:
legnth --> length

https://github.com/rkillick/changepoint/blob/355e3400a67b935f57a5b2bc5c5026b9e84fccd8/R/multiple.norm.R#L394

thanks for the package!

**Comment by rkillick** [comment]
Thanks for spotting this!  We've corrected it in the development version that will be send to CRAN in the next couple of weeks.  Embarrassingly, it appeared in several places!
