### ISSUE TITLE
How to get the confidence level of each split?

### ISSUE THREAD

**Issue by sagnikbanerjee15** [rkillick/changepoint#39]
Hello,

I am using this software to detect changepoints in gene coverage data. In my case, I do not know how many change points are present in my data. Most of the time the data might not even have a "real" checkpoint. Could you please tell me how to understand the confidence of a cut-point? Is there a p-value of something that I can check?

Thank you.

**Comment by TMiguelT** [comment]
This seems to have been discussed in #18.

**Comment by rkillick** [comment]
TMiguelT is correct.
