### ISSUE TITLE
confusion over the date slot of cpt class

### ISSUE THREAD

**Issue by taylors2** [rkillick/changepoint#42]
In the cpt class man page you say that the date slot is the “date and time the changepoint analysis was run”.  However, in the following code the date slot reads as the date that I installed the package:

library("changepoint")
a <- new("cpt")
a@date   ## "Sun Aug 11 04:01:03 2019"
b <- cpt.mean(rnorm(100))
b@date   ## "Sun Aug 11 04:01:03 2019"

**Comment by rkillick** [comment]
Oooops, this should be corrected.  Thanks for spotting this!

**Comment by rkillick** [comment]
This has been fixed in the github version and will go to CRAN with the next version release.
