### ISSUE TITLE
NegBin distribution / R-GSOC'21 project?

### ISSUE THREAD

**Issue by tdhock** [rkillick/changepoint#48]
Hi again @rkillick I just wrote a project idea wiki page about a new R package for binary segmentation, https://github.com/rstats-gsoc/gsoc2021/wiki/Binary-segmentation
Would you be willing to co-mentor that project next summer? If so could you please add your info under the Mentors section on that page? (also please edit the page is there is anything unclear/incorrect)
Also I created the following table which maps gfpop distribution type values to changepoint loss function names, is that correct?

gfpop type | changepoint cost | description
-- | -- | -- 
mean | mean_norm | Normal change in mean with constant variance
variance | var_norm | Normal change in variance with constant mean
poisson | meanvar_poisson | Poisson change in mean and variance
exp | meanvar_exp | Exponential change in mean and variance
negbin | NA | Negative binomial change in mean with constant variance

In particular is it true that change in mean for negative binomial is not yet implemented in changepoint package?

**Comment by rkillick** [comment]
Sorry for the delay in getting to look at this.  Whilst this is an interesting idea I don't think we should be encouraging the use of Binary Segmentation.  I'm intrigued by the new method [here](https://arxiv.org/abs/2002.06633) which takes some of the advantages from Wild Binary Segmentation but is deterministic.

**Comment by tdhock** [comment]
I agree that we should not be encouraging use of binary segmentation, but like it or not, reviewers often ask for a comparison with binary segmentation, so it would be useful to have more complete reference implementation, at least for comparison purposes.

About the negative binomial, am I correct that it is not currently supported in changepoint package C code loss functions?

**Comment by rkillick** [comment]
That is interesting, I'm not getting reviewers asking for that.  If I do have a BinSeg comparison though I am getting comments from reviewers "should compare with WBS, not BinSeg as it fixes problems with BinSeg".  With the smaller GSOC projects, I'm less enthused about participating as it can take a while to get students on-boarded at a time when I'm typically travelling for conferences.  But a whole new BinarySegmentation package would be easier as a smaller project than adding functionality to the existing packages as it won't be necessary to understand our code.  Go on then, let's put the project forward.

You are correct that Negative Binomial isn't currently supported in changepoint.
