### ISSUE TITLE
library claims to support R version >= 3.0, fails without function from 3.1.0

### ISSUE THREAD

**Issue by matkoniecz** [rkillick/changepoint#5]
According to https://cran.r-project.org/web/packages/changepoint/index.html 

> Depends: 	R (≥ 3.0)

It is not mentioned that higher R version is recommended.

On running with `R version 3.0.2` (from Ubuntu package) I encountered

> > cpt.meanvar(data)

> Error in checkData(data) : could not find function "anyNA"

According to http://www.r-statistics.com/2014/04/r-3-1-0-is-released/

> New function anyNA(), a version of any(is.na(.)) which is fast for atomic vectors, based on a proposal by Tim Hesterberg. (Wish of PR#15239.)

So it is not present in 3.0.

Code was from https://www.gwern.net/Google%20Alerts

**Comment by rkillick** [comment]
Thanks for spotting this, i'll update the depends in the next version.
