### ISSUE TITLE
`plot` of Changepoint object is not working

### ISSUE THREAD

**Issue by auzaheta** [rkillick/changepoint#51]
I'm working with version 2.2.2 from CRAN and version 2.3.1 from GitHub. For both, the plot functionality is not working.

```r
# change in mean
y=c(rnorm(100,0,1),rnorm(100,5,1))
ansmean=cpt.mean(y)
plot(ansmean,cpt.col='blue')

Error in as.double(y) : 
  cannot coerce type 'S4' to vector of type 'double'
```

Thanks for a great job with the package.

**Comment by rkillick** [comment]
This works for me in both versions (just copied your code directly).  Was the changepoint package the last one loaded in your workspace as sometimes other packages can conflict?
I get this image:
![image](https://user-images.githubusercontent.com/16543041/96647940-7a82a780-1326-11eb-84e2-fca4f2ea680c.png)

**Comment by auzaheta** [comment]
My fault, I checked just loading `changepoint` and it works. However, when I load a package that I'm developing it creates the conflict. Thanks a lot for the hint and I'm so sorry for the false alarm.

**Comment by rkillick** [comment]
No problem, as you may have guessed, I've had the same issue before hence the suggestion to check!
