### ISSUE TITLE
Segment check or residual check?

### ISSUE THREAD

**Issue by Jiangchao3** [rkillick/changepoint#52]
Hi, killick

I have completed detecting changepoints for my data. Following your guide, I should do the assumption check according to this website [http://members.cbio.mines-paristech.fr/~thocking/change-tutorial/RK-CptWorkshop.html#checking-assumptions-if-time-allows](url). 

You provide two methods, one is segment check and the other is residual check.  Any differences between these two checks? I want to know which one should I choose? Or should I do both these two checks?

Thanks!
Jiangchao

**Comment by Jiangchao3** [comment]
I noticed that the segment check is applying the Shapiro-Wilk normality test, KS test, qqPlot, AcfPlot to each segment. It means I should test or plot N+1 times if there are N changepoints. The residual check just test and plot once. I think I should choose the residual check because my data have more than 10 changepoints.

**Comment by Jiangchao3** [comment]
@rkillick

**Comment by rkillick** [comment]
Personally, I would always use the residual check at this gives larger n and thus more power.  I have removed the segment check in the latest version of my [course](https://github.com/rkillick/intro-changepoint-course).

**Comment by Jiangchao3** [comment]
Thank you! I have noticed the change in your latest course.
