### ISSUE TITLE
Q for cpt.meanvar with method=SegNeigh and sumstat = Poisson or Exp

### ISSUE THREAD

**Issue by aaronplowther** [rkillick/changepoint#53]
Hello,

When using cpt.meanvar with method=SegNeigh and sumstat = Poisson or Exp it appears an error is raised when Q > (length(data)+2)/2. 

With sumstat = Poisson or Exp, I believe Q can be as large as length(data) since a segment of length 1 is possible.

**Comment by rkillick** [comment]
Resolved in v2.2.3 on its way to CRAN.  The limit also applied to Normal mean too.
