### ISSUE TITLE
availability of changeppoint.influence library

### ISSUE THREAD

**Issue by cdkodira** [rkillick/changepoint#55]
Where and how can I install changeppoint.influence?

**Comment by rkillick** [comment]
Thanks for your interest in this.  The changepoint.influence package isn't available quite yet.  I'll update on here when it is.  Thanks for your interest.

**Comment by rkillick** [comment]
Apologies, I forgot to update this.  We released this to CRAN last summer: https://cran.r-project.org/web/packages/changepoint.influence/index.html
